apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: start-samtale
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/pto-frontend/pto-frontend:2023.01.13_08.11-4fff74d23073
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  ingresses:
    - https://pto.dev.nav.no/arbeid/start-samtale
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
      external:
        - host: navtestb2c.b2clogin.com
  gcp:
    buckets:
      - name: start-samtale-dev
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  env:
    - name: ENFORCE_LOGIN
      value: "true"
    - name: LOGIN_REDIRECT_URL
      value: https://loginservice.dev.nav.no/login?redirect={RETURN_TO_URL}&level=Level4
    - name: TOKEN_COOKIE_NAME
      value: selvbetjening-idtoken
    - name: GCS_BUCKET_NAME
      value: start-samtale-dev
    - name: CONTEXT_PATH
      value: /arbeid/start-samtale
    - name: JSON_CONFIG
      value: >
        {
          "fallbackStrategy": "serve",
          "proxies": [
            { "from": "/veilarbvedtakinfo", "to": "http://pto-proxy/proxy/veilarbvedtakinfo" },
            { "from": "/veilarboppfolging", "to": "http://veilarbdialog.dev-fss-pub.nais.io" },
            { "from": "/veilarbdialog", "to": "http://veilarbdialog.dev-fss-pub.nais.io" }
          ],
          "redirects": [
            {
              "from": "/minside",
              "to": "{{MINSIDE_URL}}"
            },
            {
              "from": "/arbeidsrettet-dialog",
              "to": "{{ARBEIDSRETTET_DIALOG_URL}}",
              "preserveContextPath": "true"
            }
          ]
        }
